#!/usr/bin/env node
/* Build the classic-script data bundle used when index.html is opened via file://. */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const names = [
  "nodes", "edges", "connectors", "claims", "refs",
  "measurements", "scope", "source-map", "sweep", "vision", "agenda"
];
const data = Object.fromEntries(names.map(name => [
  name,
  JSON.parse(readFileSync(join(root, "data", `${name}.json`), "utf8"))
]));
const json = JSON.stringify(data)
  .replaceAll("\u2028", "\\u2028")
  .replaceAll("\u2029", "\\u2029");
const header = "/* Generated by code/build_offline_data.mjs from data/*.json. */\n";
const output = `${header}window.NEI_DATA = ${json};\n`;
writeFileSync(join(root, "data", "offline-data.js"), output, "utf8");
console.log(`wrote data/offline-data.js (${Buffer.byteLength(output)} bytes)`);
